services:

  blockchain:
    image: "cornfeedhobo/monero:${TAG:-latest}"
    user: "${UID:-1000}:${GID:-1000}"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    ports:
      - "18080:18080"
      - "18081:18081"
      - "18082:18082"
      - "18083:18083"
    tty: true
    volumes:
      - type: "bind"
        source: "${DATA_DIR:-$HOME/.bitmonero}"
        target: "/home/monero/.bitmonero"

  wallet:
    image: "cornfeedhobo/monero:${TAG:-latest}"
    links: ["blockchain"]
    user: "${UID:-1000}:${GID:-1000}"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    tty: true
    volumes:
      - type: "bind"
        source: "${DATA_DIR:-$HOME/.bitmonero}"
        target: "/home/monero/.bitmonero"
    command: >
      monero-wallet-cli
      --daemon-address="blockchain:18081"
      --trusted-daemon
